## Start with the official rocker image (lightweight Debian)
#FROM rocker/r-base:latest
FROM tsobu/r-base:3.6.2

MAINTAINER Sammy Barasa <barsamms@gmail.com>

RUN apt-get update && apt-get install -y gnupg2

## Install Java
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    openjdk-8-jdk \
    file \
    libcurl4-openssl-dev \
    libedit2 \
    libssl-dev \
    lsb-release \
    libxml2-dev \
    libpq-dev \
    libpng-dev \
    libssh2-1-dev \
    libudunits2-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    ca-certificates \
    libglib2.0-0 \
    libxext6 \
    libsm6  \
    libxrender1 \
    bzip2 \
    libsodium-dev \
    libcairo2-dev \
    zlib1g-dev \
    && update-alternatives --display java \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

RUN R CMD javareconf

## Install rJava package
RUN install2.r --error rJava && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
